kdash/adminx/urls.py
from django.urls import path

from kdash.adminx import views
from kdash.adminx.views import listing, detail, manage  #, others
from kdash.adminx.views.reports import listing as report_listing

app_name = 'kdash_adminx'


urlpatterns = [  
    # path('autocomplete/consumer-rest/<str:config_path>/', views.others.ConsumerRestSearchDAL.as_view(),
    #      name='autocomplete_consumer_rest'),
    # path('popup-related/controller/', views.others.PopupRelatedFormView.as_view(), name='popup_related_controller'),

    path('central/<str:config_path>/', views.listing.CentralDashView.as_view(), name='central'),
    path('list/<str:config_path>/', views.listing.ListDashView.as_view(), name='list'),
    path('add/<str:config_path>/', views.manage.ManageDashView.as_view(), name='add'),
    path('change/<str:config_path>/<str:pk>/', views.manage.ManageDashView.as_view(), name='change'),
    path('delete/<str:config_path>/<str:pk>/', views.manage.DeleteDashView.as_view(), name='delete'),
    path('detail/<str:config_path>/<str:pk>/', views.detail.DetailDashView.as_view(), name='detail'),

    path('reports/list/<str:config_path>/', report_listing.ReportListView.as_view(), name='report_listing'),
    path('reports/summary/<str:config_path>/', report_listing.ReportSummaryView.as_view(), name='report_summary'),
]

kdash/adminx/templates/kdash_adminx/includes/detail_display.html
{% load common_tags %}


<table class="popup-details w-100 mb-3">
    <tr>
    {% for set in detail_fields %}
        <td class="cell-container">

            <div class="card">
                {% if set.0 %}
                <div class="card-header py-1 px-2">
                    {{ set.0 }}
                </div>
                {% endif %}
                <div class="card-body p-0">
                    <table class="table table-bordered mb-0 w-100">
                    <tbody>
                    {% for x in set.1 %}
                        <tr>
                            <td class="{{ x.name }} label">{{ x.label|replace:" ,<span class='transparent'>_</span>"|safe }}</td>
                            <td class="{{ x.name }} value w-100">{{ object|dotted_dict:x.attribute|default:"-" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>

        </td>
    {% endfor %}
    </tr>
</table> 

kdash/adminx/templates/kdash_adminx/includes/detail_options.html
{% load display_fields common_tags %}


<div class="btn-group" role="group">
    <a href='#' class="btn btn-outline-secondary btn-xs straight-edges" data-toggle="modal" data-target="#detail-modal_{{ obj.pk }}">Details</a>

    {% if actions %}
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-secondary dropdown-toggle btn-xs straight-edges" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">                                              
            <span class="caret"></span>
        </button>
        <div class="dropdown-menu dropdown-menu-right straight-edges p-0" aria-labelledby="btnGroupDrop1">
            {% for url_dict in actions %}
                <a class="dropdown-item dropdown-item-xs {{ url_dict.class }}" 
                    href='{{ obj|generate_url_from_dict:url_dict }}'>
                    {% if url_dict.icon %}<i class="fa fa-{{ url_dict.icon }}"></i>{% endif %}
                    {{ url_dict.label }}
                </a>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    
</div>


{% if fields.detail_fields %}
<div class="modal fade adminx" id="detail-modal_{{ obj.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content straight-edges">
            <div class="modal-header py-2 bg-brand straight-edges">
                <h5 class="modal-title" id="exampleModalLabel">Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <a href='{% url "kdash_adminx:detail" config_path obj.pk %}'
                   class="btn btn-info btn-xss straight-edges pull-right mb-2 view-full-details">
                    <i class="fa fa-eye"></i> View full details 
                </a>
                
                {% include "kdash_adminx/includes/detail_display.html" with detail_fields=fields.detail_fields object=obj %}
                
            </div>
        </div>
    </div>
</div>
{% endif %}