kdash/urls.py
from django.urls import path
from kdash import views

app_name = 'kdash'

urlpatterns = [
    path('proxy-filter/', views.ProxyFilterView.as_view(), name='proxy_filter'),
]

kdash/adminx/views/base.py
from django.urls import reverse
from django.views.generic import TemplateView
from django.http import Http404
from django.db import models
from django.template.defaultfilters import floatformat
from django.contrib.humanize.templatetags.humanize import intcomma

from kdash.adminx.utils import get_config_class
from kdash.adminx.constants import KDASH_ADMINX_K, KdashAdminxK
from kdash.adminx.forms import FilterOptionsForm


class AdminxBase(TemplateView):
    handler_classes = {}
    admin_type = 'base'
    
    def dispatch(self, request, *args, **kwargs):
        self.initialize(**kwargs)
        return super(AdminxBase, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):    
        context = super(AdminxBase, self).get_context_data(*args, **kwargs)  
                 
        context.update({ 
            'config_path': self.config_path,
            'config_class': self.get_config_class()
        }) 

        context.update(self.get_config_context(self.request, **kwargs))

        return context

    def initialize(self, **kwargs):
        self.workspace = self.request.workspace
        
        self.config_path = kwargs['config_path']
        try:
            self.config_class = self.get_config_class(**kwargs)
        except ImportError:
            raise Http404('Resource not found: %s. Check the path of the kdash config file' % self.config_path)

        self.config_class_type = self.get_config_class_type(**kwargs)
        self.handler_class = self.get_handler_class(**kwargs)
        self.handler = self.get_handler()

        if self.config_class_type == KDASH_ADMINX_K['CONFIG_TYPE_DJANGO']:
            self.model_class = self.get_model_class(**kwargs)

        if self.config_class_type == KDASH_ADMINX_K['CONFIG_TYPE_REST']:
            self.consumer_class = self.get_consumer_class(**kwargs)

    def get_handler_class(self, **kwargs):
        return self.handler_classes.get(self.config_class_type, None)

    def get_handler(self):
        if self.handler_class:
            return self.handler_class(adminx=self, request=self.request)

    def get_config_class(self, **kwargs):
        return get_config_class(self.config_path)

    def get_config_class_type(self, **kwargs):
        return self.config_class._config_type

    def get_consumer_class(self, **kwargs):
        return self.config_class.consumer_class 

    def get_model_class(self, **kwargs):
        return self.config_class.model_class

    def process_fields(self, raw_fields):
        xs = []
        for f in raw_fields:
            if type(f) == str:
                f = {'name': f}
                
            name = f['name']
            name_label = ' '.join(name.split('_')).capitalize()

            attribute = f.get('attribute', name)
            label = f.get('label', name_label)

            xs.append({
                'name': name, 
                'label': label, 
                'attribute': attribute
            })
        return xs

    def get_template_names(self):
        """ Get possible template names in this order
            1. Custom template defined in attribute in config class
            2. Custom template under platform folder and app and model name
            3. Custom template under app folder
            4. Default template defined under AdminxBase class

            Eg: If platform==hr, app=='entities', model='supplier'
            1. hr/registered_supplier.html
            2. hr/listing_entities_supplier.html
            3. hr/listing.html
            4. kdash_adminx/listing.html
        """
        templates = []
        
        # 1
        if self.config_class.listing_template:
            templates.append(self.config_class.listing_template)

        app_components = self.get_app_components()
        app_components.update({'admin_type': self.admin_type})

        # 2
        plat_app_model = '%(platform)s/%(admin_type)s_%(app)s_%(model)s.html' % app_components
        templates.append(plat_app_model)
        
        # 3 
        plat_only = '%(platform)s/%(admin_type)s.html' % app_components
        templates.append(plat_only)

        # 4
        def_tempt = 'kdash_adminx/%(admin_type)s.html' % app_components
        templates.append(def_tempt)
        
        return templates

    def get_config_context(self, request, **kwargs):
        return self.config_class().get_extra_context(request, **kwargs)

    def get_dash_name(self):
        return self.config_path 

    def get_app_components(self):
        platform_name, app_model = self.config_path.split(':')
        section = ''
        if '-' in app_model:
            app_model, section = app_model.split('-')

        app, model = app_model.split('.')

        return {
            'platform': platform_name,
            'app': app,
            'model': model,
            'section': section
        }

    def get_headers(self, request, keys=[]):
        keys = keys or [KDASH_ADMINX_K['HEADER_KEY_AUTH_TOKEN'], 
                        KDASH_ADMINX_K['HEADER_KEY_WORKSPACE']]
        headers = {}

        if KDASH_ADMINX_K['HEADER_KEY_AUTH_TOKEN'] in keys:
            if request.user.is_authenticated:
                profile = request.user.profile
                headers.update({
                    "Authorization": "Token %s" % profile.description
                })

        # if KDASH_ADMINX_K['HEADER_KEY_WORKSPACE'] in keys:
        #     from transact.ega.utils import get_user_details
        #
        #     user_details = get_user_details(request)
        #     workspace_dt = user_details.get('workspace', {}).get('current', {})
        #     workspace_guid = workspace_dt.get('workspace__guid', None)
        #     if workspace_guid:
        #         headers.update({
        #             "WORKSPACEGUID": workspace_guid
        #         })
        
        return headers
        

class BaseConfig(object):
    config_path = ''
    manage_class = None
    filter_class = None
    lookup_class = None

    paginate_by = 20
    can_view_detail = True
    can_add = True
    can_change = True
    can_delete = True
    can_filter = True
    can_sort = True

    sort_fields = []
    list_fields = []
    list_summary_fields = []  # Used on listing for quick detail popup page
    detail_fields = []
    list_filters = {}
    manage_fields = {}
    list_page_actions = []
    actions = []  # TODO: Rename to list_row_actions

    listing_template = ''
    detail_template = ''
    manage_template = ''

    # Reports
    filter_options_class = FilterOptionsForm
    filter_formats = (('preview', 'Preview'), ('excel', 'Excel'))
    filter_layout = KdashAdminxK.FILTER_LAYOUT_AS_MODAL.value
    summary_layout = KdashAdminxK.SUMMARY_LAYOUT_MODAL.value
    sub_filter_classes = []
    report_summary_fields = []
    export_as_excel = False

    def get_list_url(self, **kwargs): 
        config_path = kwargs['config_path']
        return reverse('kdash_adminx:list', args=(config_path,))

    def get_add_url(self, **kwargs): 
        config_path = kwargs.get('config_path', self.config_path)
        if self.can_add: 
            return reverse('kdash_adminx:add', args=(config_path,))
    
    def get_change_url(self, pk, **kwargs):
        config_path = kwargs.get('config_path', self.config_path) 
        if self.can_change: 
            return reverse('kdash_adminx:change', args=(config_path, pk))

    def get_delete_url(self, pk, **kwargs):
        config_path = kwargs.get('config_path', self.config_path) 
        if self.can_delete: 
            return reverse('kdash_adminx:delete', args=(config_path, pk))

    def get_detail_url(self, pk, **kwargs):
        if pk:
            config_path = kwargs.get('config_path', self.config_path) 
            return reverse('kdash_adminx:detail', args=(config_path, pk))

    def get_extra_context(self, *args, **kwargs):
        return {
            'config_perms': {
                'can_view_detail': self.can_view_detail,
                'can_add': self.can_add,
                'can_change': self.can_change,
                'can_delete': self.can_delete,
                'can_filter': self.can_filter,
            }
        }

    def get_extra_form_data(self, request, data, **kwargs):
        return {}


class BaseDjangoConfig(BaseConfig):
    _config_type = KDASH_ADMINX_K['CONFIG_TYPE_DJANGO']

    model_class = None

    def get_extra_filters(self, request, filters):
        return filters

    def get_extra_queryset(self, request, filters, sub_filters=None):
        return self.model_class.objects.filter(**filters)

    def get_summary(self, request, queryset):
        xs = []

        for x in self.report_summary_fields:
            val = queryset.aggregate(val=models.Sum(x['name']))['val']
            val = intcomma(floatformat(val, 2))
            xs.append({
                'name': x['name'],
                'label': x['label'],
                'value': val
            })
        return xs


class BaseRestConfig(BaseConfig):
    _config_type = KDASH_ADMINX_K['CONFIG_TYPE_REST']

    consumer_class = None


class BaseDjangoReportConfig(BaseDjangoConfig):
    filter_layout = KdashAdminxK.FILTER_LAYOUT_AS_SIDEBAR.value


class BaseHandler(object):
    
    def __init__(self, adminx, request):
        self.adminx = adminx
        self.request = request

kdash/templates/kdashmin/base.html
{% extends 'kdash/base.html' %}
{% load i18n admin_urls static admin_modify %}

{% block head %}
    <link rel="stylesheet" type="text/css" href='{% static "kdashmin/css/dj_admin.css" %}'>
    <link rel="stylesheet" type="text/css" href='{% static "kdashmin/css/admin.css" %}'>
    {% block extrahead %}{% endblock %}
    {% block extrastyle %}{% endblock %}
    {% block responsive %}
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
        {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
    {% endblock %}
{% endblock %}


{% block bodyclass %}kdashmin{% endblock %}

{% block all_right_content %}
<div class="kdashmin-main">
    {% block pretitle %}{% endblock %}
    {% block content_title %}{% endblock %}

    <div class="row">
        {% block content_row %}
        <div class="col-9">
            <div class="card dash-main">
                <div class="card-body dash-main shadowy">
                    {% block right_content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <div class="col-3">
            {% block right_content_side %}
            {% endblock %}
        </div>
        {% endblock %}
    </div>
</div>
{% endblock %}


{% block foot %}
{% endblock %}

kdash/templates/kdashmin/base_site.html
{% extends "kdashmin/base.html" %}

kdash/templates/kdashmin/change_form.html
{% extends "kdashmin/base_site.html" %}
{% load i18n admin_urls static admin_modify web_tags %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content_title %}
    <h4>{{ title }}</h4>
{% endblock %}

{% block right_content_side %}
<!-- This is only for javascript files to get id of change object -->
<span style="display: none" id="id_original_object">{{ original.pk }}</span>
<span style="display: none" id="id_original_app_model">{{ opts.app_label }}.{{ opts.model_name }}</span>

{% if change %}
    {% if not is_popup and original.get_absolute_url %}
        {% block object-tools-items %}
            <div class="module full">
                <table class="table table-bordered">
                  <caption>Actions</caption>
                   <tbody>
                        {% comment %}
                        <tr>
                            <td><a href="history/" class="historylink">{% trans "History" %}</a></td>
                        </tr>
                        {% endcomment %}
                        <tr>
                            <td>
                                <a href="{{ original.get_absolute_url }}" class="viewsitelink">{% trans "View details" %}</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {% for action in original|get_admin_actions:request %}
                <div class="module full">
                    <table>
                        <caption>{{ action.name }}</caption>
                        <tbody>
                        {% for x in action.urls %}
                            <tr>
                                <td>
                                    <a href="{{ x.1 }}" {{ x.2 }}>{{ x.0 }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endfor %}
        {% endblock %}
    {% endif %}
{% endif %}

{% endblock %}

{% block right_content %}<div id="content-main">

<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}

{% if adminform.fieldsets|length > 1 %}
    <table style="width: 100%; margin-bottom: 15px">
        {% for fieldset in adminform %}
            {% if forloop.counter0|divisibleby:2 %}<tr>{% endif %}
                <td class="fieldset-box" style="border:1px solid #ccc; padding: 0; margin: 5px"
                    {% if not adminform.fieldsets|length|divisibleby:2 and forloop.counter == adminform.fieldsets|length %}colspan="3"{% endif %}>
                    {% include "admin/includes/fieldset.html" %}
                </td>
                {% if forloop.counter0|divisibleby:2 %}
                    {% if not forloop.last %}
                    <td style="border: none; width: 10px"></td>
                    {% endif %}
                {% else %}
                    <tr style="border: none; height: 15px"></tr>
                {% endif %}
            {#{% if forloop.counter0|divisibleby:2 %}</tr>{% endif %}#}
        {% endfor %}
    </table>
{% else %}
    <table style="width: 100%; margin-bottom: 15px">
        <tr>
            <td style="border:1px solid #ccc;">
                {% for fieldset in adminform %}
                    {% include "admin/includes/fieldset.html" %}
                {% endfor %}
            </td>
        </tr>
    </table>
{% endif %}

{% endblock %}

<!-- <br /> -->

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% block admin_change_form_document_ready %}
    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="{% static 'admin/js/change_form.js' %}"
            {% if adminform and add %}
                data-model-name="{{ opts.model_name }}"
            {% endif %}>
    </script>

    <script type="text/javascript">
        function isFormHtml5Valid(form) {
            for (var el of form.querySelectorAll('input,textarea,select')) {
                if(!el.checkValidity())
                    return false;
            }
            return true;
        }

        (function($) {
            $(document).ready(function() {
                $('.add-another').click(function(e) {
                    e.preventDefault();
                    showAddAnotherPopup(this);
                });
                $('.related-lookup').click(function(e) {
                    e.preventDefault();
                    showRelatedObjectLookupPopup(this);
                });
            {% if adminform and add and not adminform.model_admin.allow_serial_scan %}
                $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
            {% endif %}

            $('.submit-row input').click(function(e) {
                // e.preventDefault();
                // $('.submit-row input').css('display', 'none');
                // $('.submit-row select').css('display', 'none');

                $(".submit-row :input").each(function(){
                    // $(this).prop('disabled', true);
                    $(this).css('display', 'none');
                })
                // this.form.submit();

                url = '{% static "website/local/img/loading.gif" %}';
                img_html = '<img src="' + url +'" />'
                $('.submit-row #id_loading').html(img_html);
            });

            });
        })(django.jQuery);

    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}




mySubmitButton.onclick = function() {
  if(this.form && isFormHtml5Valid(this.form))
    this.disabled=true;
  this.form.submit();
}

kdash/templates/kdashmin/change_list.html
{% extends "kdashmin/base_site.html" %}
{% load i18n admin_urls static admin_list %}
{% load template_design humanize %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
  {% endif %}
  {% if cl.formset or action_form %}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% if action_form %}{% if actions_on_top or actions_on_bottom %}
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
{% endif %}{% endif %}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ cl.opts.app_config.verbose_name }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}

{% block content_title %}
  <h1>{{ custom_verbose_name_plural|default:cl.opts.verbose_name_plural|title }}</h1>
{% endblock %}


{% block right_content %}
  <div id="content-main">

    {% if cl.formset.errors %}
        <p class="errornote">
        {% if cl.formset.total_error_count == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}

    <div class="module{% if cl.has_filters_ %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      <form id="changelist-form" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
{% endblock %}


{% block right_content_side %}
    {% block object-tools %}
        {% if has_add_permission or cl.opts.model.changelist_links or objectactions %}
        <div class="module full">
            <table class="table table-bordered">
                <caption>Actions</caption>
                <tbody>
                {% if has_add_permission %}
                    <tr>
                      <td>
                        <a href="add/{% if custom_add_params %}{{ custom_add_params }}{% endif %}{% if is_popup %}?_popup=1{% endif %}" class="addlink">
                        {% if custom_verbose_name %}
                            Add {{ custom_verbose_name }}
                        {% else %}
                          {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
                        {% endif %}
                        </a>
                      </td>
                    </tr>
                {% endif %}

                {% for action in cl.opts.model.changelist_links %}
                <tr>
                    <td>
                        <a href="{{ action.1 }}" class="{{ action.2 }}">{{ action.0 }}</a>
                    </td>
                </tr>
                {% endfor %}

                {% for tool in objectactions %}
                    <tr class="objectaction-item" data-tool-name="{{ tool.name }}">
                        <td>
                        {% url tools_view_name tool=tool.name as action_url %}
                        <a href="{% add_preserved_filters action_url %}" title="{{ tool.standard_attrs.title }}"
                            {% for k, v in tool.custom_attrs.items %}
                                {{ k }}="{{ v }}"
                            {% endfor %}
                            class="{{ tool.standard_attrs.class }}">
                            {{ tool.label|safe }}
                        </a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        {% endif %}
    {% endblock %}

    {# list_summary cl.opts.app_label cl.opts.model_name cl.result_list #}
    {% if value_summary %}
        <table class="module full" style="width: 100%">
            <caption>Overview</caption>
            <tbody>
                {% for t in value_summary %}
                    <tr>
                        <td>{{ t.0|capfirst }}</td>
                        <td>{{ t.1|floatformat:2|intcomma }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% block filters %}

        {% if cl.has_filters %}
            {% if filter_form %}
                <div class="module full filter-form">
                    <form action='{% url "kdash:proxy_filter" %}' method="get">

                        <table class="table table-bordered filter-table">
                            <caption>Filters</caption>
                            {{ filter_form.as_table }}

                            <tr>
                                <td>
                                    <a href="." class="small mt-2">Reset filters</a>
                                </td>
                                <td>
                                    <button type="submit" class="btn btn-primary btn-sm float-right">Filter</button>
                                </td>
                            </tr>
                        </table>

                    </form>
                </div>
            {% else %}
                <div class="module">
                <div id="changelist-filter">
                    <h2>{% trans 'Filter' %}</h2>
                    {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
                </div>
                </div>
            {% endif %}
        {% endif %}

      {% endblock %}

{% endblock %}

kdash/templates/kdashmin/delete_confirmation.html
{% extends "kdashmin/base_site.html" %}
{% load i18n admin_urls static %}

{% block extrahead %}
    {{ block.super }}
    {{ media }}
    <script type="text/javascript" src="{% static 'admin/js/cancel.js' %}"></script>
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} delete-confirmation{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'change' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
&rsaquo; {% trans 'Delete' %}
</div>
{% endblock %}

{% block right_content %}
{% if perms_lacking %}
    <p>{% blocktrans with escaped_object=object %}Deleting the {{ object_name }} '{{ escaped_object }}' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:{% endblocktrans %}</p>
    <ul>
    {% for obj in perms_lacking %}
        <li>{{ obj }}</li>
    {% endfor %}
    </ul>
{% elif protected %}
    <p>{% blocktrans with escaped_object=object %}Deleting the {{ object_name }} '{{ escaped_object }}' would require deleting the following protected related objects:{% endblocktrans %}</p>
    <ul>
    {% for obj in protected %}
        <li>{{ obj }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>{% blocktrans with escaped_object=object %}Are you sure you want to delete the {{ object_name }} "{{ escaped_object }}"? All of the following related items will be deleted:{% endblocktrans %}</p>
    {% include "admin/includes/object_delete_summary.html" %}
    <h2>{% trans "Objects" %}</h2>
    <ul>{{ deleted_objects|unordered_list }}</ul>
    <form method="post">{% csrf_token %}
    <div>
    <input type="hidden" name="post" value="yes">
    {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1">{% endif %}
    {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}">{% endif %}
    <input type="submit" value="{% trans "Yes, I'm sure" %}">
    <a href="#" class="button cancel-link">{% trans "No, take me back" %}</a>
    </div>
    </form>
{% endif %}
{% endblock %}

kdash/templates/kdashmin/delete_selected_confirmation.html
{% extends "kdashmin/base_site.html" %}
{% load i18n l10n admin_urls static %}

{% block extrahead %}
    {{ block.super }}
    {{ media }}
    <script type="text/javascript" src="{% static 'admin/js/cancel.js' %}"></script>
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} delete-confirmation delete-selected-confirmation{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; {% trans 'Delete multiple objects' %}
</div>
{% endblock %}

{% block right_content %}
{% if perms_lacking %}
    <p>{% blocktrans %}Deleting the selected {{ objects_name }} would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:{% endblocktrans %}</p>
    <ul>
    {% for obj in perms_lacking %}
        <li>{{ obj }}</li>
    {% endfor %}
    </ul>
{% elif protected %}
    <p>{% blocktrans %}Deleting the selected {{ objects_name }} would require deleting the following protected related objects:{% endblocktrans %}</p>
    <ul>
    {% for obj in protected %}
        <li>{{ obj }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>{% blocktrans %}Are you sure you want to delete the selected {{ objects_name }}? All of the following objects and their related items will be deleted:{% endblocktrans %}</p>
    {% include "admin/includes/object_delete_summary.html" %}
    <h2>{% trans "Objects" %}</h2>
    {% for deletable_object in deletable_objects %}
        <ul>{{ deletable_object|unordered_list }}</ul>
    {% endfor %}
    <form method="post">{% csrf_token %}
    <div>
    {% for obj in queryset %}
    <input type="hidden" name="{{ action_checkbox_name }}" value="{{ obj.pk|unlocalize }}">
    {% endfor %}
    <input type="hidden" name="action" value="delete_selected">
    <input type="hidden" name="post" value="yes">
    <input type="submit" value="{% trans "Yes, I'm sure" %}">
    <a href="#" class="button cancel-link">{% trans "No, take me back" %}</a>
    </div>
    </form>
{% endif %}
{% endblock %}